### ISSUE TITLE
Feature request: broadcast only to one peer (Private transaction broadcasting)

### ISSUE THREAD

**Issue by starius** [alfred-hodler/pushtx#1]
There is some research that if a transaction is broadcasted to many peers simultaneously, it is easier to detect the source of the transaction.

https://docs.wasabiwallet.io/why-wasabi/NetworkLevelPrivacy.html#private-transaction-broadcasting-1

https://github.com/bitcoin/bips/blob/master/bip-0156.mediawiki

I propose to broadcast to a random peer and disconnect the peer (but keep the connection open with other peers). If Tor is available, use only onion peers. Then wait for some time, if the transaction is sent back by any other peer. If this happens, consider the transaction successfully broadcasted. Otherwise, if after some time it is still not sent back, send it to another random peer etc. Disconnect the peer after sending to it immediately, but don't disconnect other peers for some time. Wait for some random time for each peer after successfully receiving the transaction back, then close the connection. If it stops right after receiving the transaction, this can be used as heuristics to detect the link between the connection and the transaction.

**Comment by alfred-hodler** [comment]
To address this, we could probably have multiple broadcast strategies:

a) when using Tor, keep the current strategy (broadcast to many peers at once for the sake of speed)
b) when using clearnet, use the strategy you outline above

I think that if we're coming through a fresh Tor circuit for every broadcast, it doesn't really matter if we are being surveilled since there is nothing of value to learn. At worst, the adversary sees that the transaction came through Tor.

The current broadcast strategy is fast and generates a high confidence level that a transaction indeed went out. The time spent broadcasting is minimal. The problem with broadcasting to a single peer is that it can fail at various stages and takes more time, including the time spent watching for the `inv` message from other peers advertising our own transaction to us.

Thoughts?

**Comment by starius** [comment]
I propose to add a flag for the strategy:
```
--strategy=[private|fast]
```
Then people would choose what they prefer. I would keep default "private" though just to increase to anonymity set of people sending transactions in a private manner.

I would like to use the private strategy even through Tor, because an adversary can happen to sit on the network channel between me and Tor and detect transaction broadcast network pattern. I think it is possible to correlate Tor traffic produced by sending to many peers at the same time with new transaction appearing publicly (in adversary's mempool). Given the fact that different transactions often have different sizes (and it affects the amount of Tor traffic) and not many transactions are broadcasted at the same time in the network, I think it is possible to detect the exact transaction, exploiting the the knowledge that majority sends to all the peers simultaneously.

**Comment by alfred-hodler** [comment]
Indeed, it seems best to offer the choice of both strategy and network type. That way we end up with a matrix of options where the user can mix and match the tradeoffs they're comfortable with.

I'll put this on the roadmap for the next version.

**Comment by vasild** [comment]
> --strategy=[private|fast]

Looks like using the Tor network is both private and fast because you can submit to a few peers simultaneously. While using clearnet is less private (but more private compared to sending to centralized block explorers) and slow because you wait for a tx roundtrip before sending to another peer. Right?

**Comment by alfred-hodler** [comment]
@starius I believe this PR does what you proposed: https://github.com/alfred-hodler/pushtx/pull/5

Transaction propagation is much faster than I expected so we don't need to send to multiple peers at all.

**Comment by starius** [comment]
@vasild 

> > --strategy=[private|fast]
> 
> Looks like using the Tor network is both private and fast because you can submit to a few peers simultaneously. While using clearnet is less private (but more private compared to sending to centralized block explorers) and slow because you wait for a tx roundtrip before sending to another peer. Right?

Even with onion peers it is better for privacy to send to one peer and wait. If you send to many onion peers, your ISP will see a spike of Tor traffic on your connection and can correlate it with appearance of a transaction in mempool.

**Comment by alfred-hodler** [comment]
Resolved in #5 .
